sonar.projectKey=utilForever_urbanflow
sonar.organization=utilforever-github
sonar.host.url=https://sonarcloud.io

sonar.sources=src
sonar.exclusions=target/**
sonar.rust.lcov.reportPaths=target/llvm-cov/lcov.info
